小的改动
gittestapi/gittest pull request #45
Opened 2017-12-16 04:17 UTC by liuditai

2017-12-16 06:45 UTC, yangzhenping requested changes
2 typos, please correct them, thanks.

2017-12-16 06:45 UTC, yangzhenping commented on basic/views/test-excution/my-missions.php
> +                        return 'complated';
typo, completed, thanks.

2017-12-17 09:31 UTC, liuditai commented
拼写错误修改完成

2017-12-17 10:55 UTC, yangzhenping approved these changes
thank you!

2017-12-17 10:56 UTC, merged